### ISSUE TITLE
Dopamine Modulation

### ISSUE THREAD

**Issue by PaollaFD** [Hjorthmedh/Snudda#126]
Dear devs,

I would like to add dopamine modulation to my simulations, through change in the conductances, as it is explained on "The microcircuits of striatum in silico" article. I was able to find the functions related to this mechanism on the simulate.py, but couldn't understand where they are used. Is there a way to set the time interval for when I would like to insert the modulation? If you could shed some light on this issue, it would be of great help!

Thank you

**Comment by Hjorthmedh** [comment]
Hej Paolla, sorry for the slow reply. We are in the process of updating the neuromodulation so that the code is more generic with support for more than just dopamine. Johanna is working on the  gpcr_modulation branch, and we should have it merged into the main branch within the next few weeks.

**Comment by Hjorthmedh** [comment]
Hej Paolla, the neuromodulation branch has been merged into the dev branch a week or so ago. I think Johanna has a few Jupyter notebooks that show how it is used.

**Comment by jofrony** [comment]
Hej Paolla, 

As @Hjorthmedh pointed out, for neuromodulation is on the dev branch currently, hence use this branch for your installation. Examples of how to use neuromodulation are in examples-folder at https://github.com/jofrony/Neuromodulation-software
