### ISSUE TITLE
Section access unspecified (Less workers than neurons)

### ISSUE THREAD

**Issue by bosse89** [Hjorthmedh/Snudda#172]
Error message:
11 x86_64/special: Section access unspecified

Happens in 'Snudda simulate' when there are more workers than there are neurons. I think it only happens when also saving voltage (--voltOut outfile.txt).

Temporary solution:
Just make sure there are less workers (#SBATCH ntasks=5) than neurons (snudda init jobdir --size 10) in the network.

**Comment by Hjorthmedh** [comment]
Thanks, I will look into this later.

**Comment by Hjorthmedh** [comment]
Added a check that num_neurons >= num_workers in simulate.py
