### ISSUE TITLE
out-of-memory error

### ISSUE THREAD

**Issue by bosse89** [Hjorthmedh/Snudda#173]
When creating/simulating large networks on a high performance cluster (e.g. CSCS) one can an ​out-of-memory error similar to:
###########################################################################################
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=32962413.0 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
###########################################################################################

Large files are likely overloading the RAM for each compute node.

**Temporary solution:**
Try adjusting #SBATCH --tasks-per-node
e.g. 
`#SBATCH --tasks-per-node=5`

The following example SBATCH settings worked for 100 000 neurons at CSCS.

```
#!/bin/bash -l
#SBATCH --job-name=Simulate100k
#SBATCH --ntasks=500
#SBATCH --cpus-per-task=1
#SBATCH --tasks-per-node=5
#SBATCH --account=ich030
#SBATCH --time=23:58:00
#SBATCH --partition=normal
#SBATCH --constraint=mc
```

**Solution:** 
There are large nodes at CSCS that might enable larger simulations (--mem=120GB). (At CSCS the normal nodes have 64GB of memory while the high memory ones have 128GB.)
Also maybe we could write some more guidelines for optimizing ntasks, tasks-per-node, cpus-per-task etc.
At least for one cluster (e.g. CSCS) such that other Snudda users could better generalize to their own non-CSCS clusters.

**Comment by Hjorthmedh** [comment]
Yes, reducing the tasks per node can help as there is some duplication of data between tasks. 
Closing this ticket for now.
