### ISSUE TITLE
'Snudda input' mpi error: Fatal error in PMPI_Init_thread

### ISSUE THREAD

**Issue by bosse89** [Hjorthmedh/Snudda#176]
When running 'snudda input' on CSCS according to the example (CSCS) files in 'Snudda/examples/parallel',
I get the following error when running CSCS_daint_setup_input.job (also same error when integrating it to CSCS_daint_runSnudda.sh):

**Error:**
#######################################################################
Mon Aug  2 13:19:54 2021: [unset]:_pmi_alps_init:alps_get_placement_info returned with error -1
Mon Aug  2 13:19:54 2021: [unset]:_pmi_init:_pmi_alps_init returned -1
[Mon Aug  2 13:19:54 2021] [c0-0c0s2n0] Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(537): 
MPID_Init(246).......: channel initialization failed
MPID_Init(647).......:  PMI2 init failed: 1 
/var/spool/slurmd/job32939909/slurm_script: line 69: 11647 Aborted                 (core dumped) snudda input ${JOBDIR}
#######################################################################

**Temprary solution:**
Run CSCS_daint_setup_input.job in non-parallel mode (ie. with ntasks=1), separate it in to a job and shell script and call that script from the job file using 'srun'.
Example job file:

```
#!/bin/bash -l
#SBATCH --job-name=SnuddaInput
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --account=ich030
#SBATCH --time=04:00:00
#SBATCH --partition=normal
#SBATCH --constraint=mc
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}

module load daint-mc
module swap PrgEnv-cray PrgEnv-gnu
source $SCRATCH/snudda_env/bin/activate

chmod +x CSCS_daint_setup_input_Script_nopara.sh
srun ./CSCS_daint_setup_input_Script_nopara.sh 
```

Example script file:
```
#!/bin/bash
JOBDIR=networks/test100

########## Needed for NEURON
L=$SCRATCH/snudda_env
LN=$L/neuron
export PATH=$L/bin:$LN/bin:$PATH
export LD_LIBRARY_PATH=$MPICH_DIR/lib:$LD_LIBRARY_PATH
export PYTHONPATH=$L/lib/python3.8/site-packages:$PYTHONPATH
export PYTHONPATH=$LN/lib/python:$PYTHONPATH
########### Needed for NEURON end.

echo ">>> Running sundda input"
snudda input $JOBDIR --input input_config/striatum-test-input.json 
```

This non-parallel version has been quite fast so far (using 'striatum-test-input.json' from the examples).
Snudda input only (On CSCS daint)
100 neurons, ntasks=1,          1min 27sek
1000 neurons, ntasks=1,        2min 20sek
10 000 neurons, ntasks=1,     13min 12sek
50 000 neurons, ntasks=1,     1h 6min
100 000 neurons, ntasks=1,   2h 7min 
150 000 neurons, ntasks=1,   3h 20min 

**Solution:**
Don't know.

**Comment by Hjorthmedh** [comment]
I noticed that the parallel execution still happened in serial for the input. I have updated the "doc" branch with code to fix that, still need to check if that helps with the MPI error you got on CSCS.

**Comment by Hjorthmedh** [comment]
Tue Aug 24 09:48:41 2021: [unset]:_pmi_alps_init:alps_get_placement_info returned with error -1
Tue Aug 24 09:48:41 2021: [unset]:_pmi_init:_pmi_alps_init returned -1
[Tue Aug 24 09:48:41 2021] [c6-0c1s11n1] Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(537): 
MPID_Init(246).......: channel initialization failed
MPID_Init(647).......:  PMI2 init failed: 1 
/var/spool/slurmd/job33371969/slurm_script: line 75: 70253 Aborted   

Still got the same error, which is curious, as the MPI works for the other parts of Snudda.
