### ISSUE TITLE
Hdf5 file locked by 'SnuddaDetect': permission denied when attempting to remove temporary hdf5 files

### ISSUE THREAD

**Issue by bosse89** [Hjorthmedh/Snudda#177]
Inspired by the example notebook: https://github.com/Hjorthmedh/Snudda/blob/master/examples/notebooks/striatum_example.ipynb
I'm creating a network with 10 neurons and running all functions directly after each other (init, place, detect, prune, input, simulate). A PermissionDenied bug appears when coming to the Prune function. I added some extra prints for clarity:

**Error:**
#########################################################################
D:\code\python\pycharmProjects\snudda-01\venvCB\Scripts\python.exe D:/code/python/pycharmProjects/snudda-01/main.py

STARTING SnuddaInit
Adding Striatum with 10 neurons
Using cube for striatum
Adding neurons: dSPN from dir $DATA\neurons\striatum\dspn
Adding neurons: iSPN from dir $DATA\neurons\striatum\ispn
Writing networks/testnetwork1\network-config.json

STARTING SnuddaPlace

STARTING SnuddaDetect
No d_view specified, running distribute neurons in serial
Processing hyper voxel : 0/48 (10 neurons)
Processing hyper voxel : 1/48 (10 neurons)
Processing hyper voxel : 4/48 (10 neurons)
Processing hyper voxel : 5/48 (10 neurons)
Processing hyper voxel : 16/48 (9 neurons)
Processing hyper voxel : 20/48 (8 neurons)
Processing hyper voxel : 21/48 (8 neurons)
Processing hyper voxel : 17/48 (7 neurons)
Processing hyper voxel : 2/48 (1 neurons)
Processing hyper voxel : 6/48 (1 neurons)
Processing hyper voxel : 9/48 (1 neurons)

STARTING SnuddaPrune
Read 1575 out of total 1575 synapses
Traceback (most recent call last):
  File "D:/code/python/pycharmProjects/snudda-01/main.py", line 41, in <module>
    sp.prune()
  File "D:\code\python\pycharmProjects\snudda-01\venvCB\lib\site-packages\snudda\detect\prune.py", line 260, in prune
    self.cleanup()
  File "D:\code\python\pycharmProjects\snudda-01\venvCB\lib\site-packages\snudda\detect\prune.py", line 2063, in cleanup
    os.remove(f)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'networks/testnetwork1\\temp\\gapJunctions-for-neurons-0-to-10-MERGE-ME.hdf5'

Process finished with exit code 1
#########################################################################

Happens when SnuddaDetect is in the same python process as SnuddaPrune.
It seems SnuddaDetect somehow uses the temp files/folder and does not finish this process or close/unclock the files. Although closing files manually “self.hist_list.close()” before os.remove(file) does not help.

Example code that generates the error:
```
import os
network_path = os.path.join("networks/testnetwork1")

print('\nSTARTING SnuddaInit')
from snudda import SnuddaInit
struct_def = {"Striatum": 10}
si = SnuddaInit(network_path=network_path, struct_def=struct_def, random_seed=123)

print('\nSTARTING SnuddaPlace')
from snudda import SnuddaPlace
spl = SnuddaPlace(network_path=network_path)
spl.place()

print('\nSTARTING SnuddaDetect')
from snudda import SnuddaDetect
sd = SnuddaDetect(network_path=network_path)
sd.detect()

print('\nSTARTING SnuddaPrune')
from snudda import SnuddaPrune
sp = SnuddaPrune(network_path=network_path)
sp.prune()
```

**Temporary solution:**
One can bypass the bug by running SnuddaDetect as a separate process from that of SnuddaPrune.
Easiest is to separate the code and run them each separately. If you are using a python notebook you could just restart the engine.
The error does seem to appear when running the code as a script on a high performance computing cluster such as CSCS.

**Solution:**
Find a way to unlock/close the h5py process that locks the file. As previously mentioned: closing files manually “self.hist_list.close()” before os.remove(file) does not seem to help.

**Comment by Hjorthmedh** [comment]
Does it help to do :

sd = None

before you start prune?

I wonder if this is Windows specific.

**Comment by Hjorthmedh** [comment]
Added a try statement around the removal, to avoid crashing the code.
