### ISSUE TITLE
Running Snudda on macOS

### ISSUE THREAD

**Issue by wthun** [Hjorthmedh/Snudda#30]
If I try to run Snudda on macOS (Catalina 10.15.7) I get an error where it can't open '/proc/meminfo' (line 1839 in simulate.py). If I change the function it works fine as I can tell by following the tinyNetwork test. I used psutil:

```
from psutil import virtual_memory

  def checkMemoryStatus(self,threshold=0.1):

    mem = virtual_memory()
    memoryRatio = mem.available / mem.total
    self.writeLog(str(self.pc.id()) + ": Memory status: " \
                  + str(int(memoryRatio * 100)) + "% free")

    return memoryRatio < threshold
```

**Comment by Hjorthmedh** [comment]
Thank you, I have incorporated it into the PEP_fix branch, should be merged into master soon.

**Comment by Hjorthmedh** [comment]
This is merged into master, and should be fixed now.
