### ISSUE TITLE
ValueError: argument not a density mechanism name.: kdr_lts

### ISSUE THREAD

**Issue by PaollaFD** [Hjorthmedh/Snudda#40]
While running the example simulation StriatumScaffoldExample-tiny.ipynb, upon executing input line [14] :

_!snudda simulate networks/tinySim/ --time 0.1 --input networks/tinySim/input-spikes.hdf5 --voltOut networks/tinySim/simulation/volt.txt_

I get the following error : 

_ValueError: argument not a density mechanism name.: kdr_lts_

I believe I might not have all the necessary packages in order to run the simulation, it could maybe be related to the different versions, I am currently using the pnas_2020 branch from the repository, How should I proceed in order to solve this problem? Should I use another branch/version, or maybe add the missing files somehow?

Thank you

**Comment by Hjorthmedh** [comment]
This sounds a problem with the compilation of neuron channel modules. Have you run nrnivmodl on cellspec-v2/mechanisms so that there is a x86_64 directory in the path you run snudda from?

**Comment by PaollaFD** [comment]
I believe I was running nrnivmodl on v1 of cellspec at first, but changing it to v2 solved my issue! Thank you
