### ISSUE TITLE
ipyparallel import SnuddaDetect

### ISSUE THREAD

**Issue by jofrony** [Hjorthmedh/Snudda#79]
Problems running population_unit_network.ipynb with ipyparallel. I was not able to run it, because SnuddaDetect import did not work. Specific error,

ModuleNotFoundError: No module named 'snudda.detect.detect'; 'snudda.detect' is not a package

**Comment by Hjorthmedh** [comment]
Is this still an issue?

**Comment by Hjorthmedh** [comment]
I have updated the version on pypi.org after merging the latest dev branch into master. This should prevent anyone from using the old version of the code with the new version of the notebooks on GitHub.
